configfile:
  - config/config.yaml
  - profiles/nextstrain/builds.yaml
  - profiles/nextstrain/s3.yaml

cores: 8
keep-going: True
printshellcmds: True
reason: True
restart-times: 1
stats: stats.json
set-threads: tree=4
