name: Rebuild open (GenBank) phylogenetic datasets

on:
  # This workflow can be triggered from repository_dispatch events,
  # for instance, after the appropriate preprocessing actions have completed
  repository_dispatch:
    types:
      - rebuild
      - open/rebuild
      - genbank/rebuild
  # Manually triggered using GitHub's UI
  workflow_dispatch:
    trial_name:
      description: "Short name for this trial build, for prefixing the uploaded data and results files. WARNING: without this we will overwrite files in s3://nextstrain-data/files/ncov/open/ and the trees on nextstrain.org/ncov/open/..."
      required: false
    image:
      description: Specific container image to use for build
      required: false

env:
  TRIAL_NAME: ${{ github.event.inputs.trial_name }}
  NEXTSTRAIN_DOCKER_IMAGE: ${{ github.event.inputs.image || 'nextstrain/base:latest' }}

jobs:
  open:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: ./scripts/setup-github-workflow

    - name: Launch build
      run: |
        set -x

        if [[ "$TRIAL_NAME" ]]; then
          BUILD_CONFIG="--config \
            S3_DST_BUCKET=nextstrain-staging/files/ncov/open/trial/${TRIAL_NAME} \
            deploy_url=s3://nextstrain-staging/ \
            auspice_json_prefix=ncov_open_trial_${TRIAL_NAME} \
          "
        else
          BUILD_CONFIG="--config slack_token=$SLACK_TOKEN"
        fi

        nextstrain build \
          --aws-batch \
          --cpus 16 \
          --memory 30GiB \
          . \
            deploy \
            upload \
            ${BUILD_CONFIG} \
            --profile nextstrain_profiles/nextstrain-open \
            --set-threads tree=16 \
        |& tee build-launch.log
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

    - name: Build info
      run: |
        if [[ "$TRIAL_NAME" ]]; then
          echo "--> Trial name is: $TRIAL_NAME"
          echo
          echo "--> Upload prefixes"
          echo "build files: s3://nextstrain-staging/files/ncov/open/trial/$TRIAL_NAME/"
          echo "nextstrain URLs: https://nextstrain.org/staging/ncov/open/trial/$TRIAL_NAME/REGION_NAME"
        else
          echo "--> Open (GenBank) phylogenetic analysis successfully rebuilt"
          echo
          echo "--> Uploaded data"
          echo "build files: s3://nextstrain-data/files/ncov/open/REGION_NAME/"
          echo "nextstrain URLs: https://nextstrain.org/ncov/open/REGION_NAME"
        fi
        echo
        echo "--> You can aso download assets from this (completed) AWS run via"
        tail -n1 build-launch.log
        echo